config/routes.rb
Rails.application.routes.draw do
  root 'roots#top'
  get '/about', to: 'roots#about'
  get '/admin_top', to: 'roots#admin_top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :destinations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update]
  resources :songs

  resources :labels, only: [:index, :new, :create, :edit, :update]
  resources :artists, only: [:index, :new, :create, :edit, :update]
  resources :orders

  get 'carts/confirm'
  get 'carts/thanks'
  resources :carts, only: [:show] do
    resources :cart_products, only: [:create, :update, :destroy]
  end


  get 'inquiries/new'
  get 'inquiries/confirm'
  post 'inquiries/confirm' => 'inquiries#confirm'
  get 'inquiries/thanks'

  get  'new' =>'inquiries#new'
  post 'thanks' => 'inquiries#thanks'

  # 開発環境メール確認用
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  post  'ajax_test/update', to: 'carts#update', as: 'ajax_test_update'
  post  'shakashaka', to: 'roots#shakashaka', as: 'ajax_shakashaka'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  belongs_to :user
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/label.rb
class Label < ApplicationRecord
has_many :products
validates :label_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products
  has_many :carts, through: :cart_products
  has_many :songs
  accepts_nested_attributes_for :songs
  has_many :artists, through: :songs
  belongs_to :label
  belongs_to :genre

  validates :explanation, presence:true,length: { maximum: 200 }
  validates :product_title, presence:true,length: { maximum: 50 }
  validates :product_price, presence: true
  validates :stock, presence: true

  # attachment :image
  has_one_attached :jacket_image

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :product

  validates :song_title, presence: true
  validates :track_order, presence: true
  validates :disk_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :user_name, presence: true, uniqueness: true, length: {maximum: 20}
  validates :user_name_kana, presence: true
  validates :postcode, length: {is:7}
  validates :address, presence: true, length: {maximum: 100}
  validates :phone_number, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  has_many :destinations
  has_one :cart, dependent: :destroy
  

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
     Cart.create(user_id: current_user.id) if current_user.present?
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,only: [:index,:show]
  before_action :authenticate_admin,only: [:index]
  before_action :authenticate_adm_or_correct_user, only: [:show, :edit, :update]

  def index
    @user = current_user
    @users = User.page(params[:page]).reverse_order
    @search = User.ransack(params[:q])
    @result = @search.result.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @orders = @user.orders.reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザーの更新に成功しました"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "ユーザーの削除に成功しました"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :user_name_kana, :postcode, :address, :phone_number,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body class="cart_show_body">
    <div class="haikei">
        <div class="col-xs-offset-5">
            <h1>ユーザー編集</h1>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
                
                    <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>
            <%= form_for(@user) do |f| %>
                <h4>ユーザー名</h4>
                <%= f.text_field :user_name %>
                <h4>かな</h4>
                <%= f.text_field :user_name_kana%>
                <h4>郵便番号</h4>
                <%= f.text_field :postcode %>
                <h4>住所</h4>
                <%= f.text_field :address %>
                <h4>電話番号</h4>
                <%= f.text_area :phone_number %>
                <div>
                <%= link_to "戻る" , user_path(@user) ,class: "btn btn-default"%>
                <%= f.submit "更新",class: "btn btn-default" %>
            <% end %>
        </div>
    </div>
</body>

app/views/users/index.html.erb
<body class="cart_show_body">
<div class="haikei">
<div class="page-holder">
<h1>ユーザー管理</h1>
<% provide(:user_name, 'All users') %>
<%= search_form_for @search  do |f| %>
  <div class="kensaku">
    <%= f.text_field :user_name_cont, class: "form-control" %>
   </div>
  <div class="kensaku1">
  <%= f.submit "検索", class: "btn btn-primary" %>
  </div>
<% end %>
 
<table class="table">
<tr>
    <th>名前</th>
    <th>メールアドレス</th>
    <th colspan="3"></th>
</tr>
<% @result.each do |user| %>
<tr>
   <td><%= user.user_name %></td>
   <td><%= user.email %></td>
   <td><%= link_to "詳細", user_path(user)%></td>
 </tr>
<% end %>
</table>
<%= paginate @users %>
</div>
</div>
</body>

app/views/users/show.html.erb
<body class="cart_show_body">
  <div class="container">
    <div class="haikei">
      <% if current_user.admin? %>
        <h1>ユーザー詳細</h1>
        <table class="table">
          <tr>
            <th>ユーザー名</th>
            <th>ユーザーかな</th>
            <th>郵便番号</th>
            <th>住所</th>
            <th>電話番号</th>
            <th>メールアドレス</th>
            <th colspan="6"></th>
          </tr>
          <td><%= @user.user_name%></td>
          <td><%= @user.user_name_kana%></td>
          <td><%= @user.postcode%></td>
          <td><%= @user.address%></td>
          <td><%= @user.phone_number%></td>
          <td><%= @user.email%></td>
          <%= link_to "編集", edit_user_path(@user),class: "btn btn-default" %>
          <%= link_to "送付先リスト", user_destinations_path(@user),class: "btn btn-default" %>
          <%= link_to "削除",user_path(@user) ,class: "btn btn-default",method: :delete, data: {confirm: "本当に削除しますか？"} unless @user.admin? %>
          <%= link_to "戻る", users_path ,class: "btn btn-default" %>
        </table>
        <h1>直近の購入履歴</h1>
        <table>
          <tr>
            <th>受注日</th>
            <th>ステータス</th>
            <th>ユーザー名</th>
            <th>注文金額</th>
            <th colspan="4"></th>
          </tr>
          <% @orders.each do |order| %>
            <tr>
              <td><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
              <td>
                <% if order.status.to_i == 10 %>
                  受付済み
                <% elsif order.status.to_i == 20 %>
                  発送準備中
                <% elsif order.status.to_i == 30 %>
                  発送済み
                <% else %>
                  確認中
                <% end %>
              </td>
              <td><%= order.user.user_name %></td>
              <td><%= order.total_price %></td> 
              <td><%= link_to "詳細", order_path(order) ,class: "btn btn-default"%></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <h1>マイページ</h1>
        <table class="table">
          <tr>
            <th>ユーザー名</th>
            <th>ユーザーかな</th>
            <th>郵便番号</th>
            <th>住所</th>
            <th>電話番号</th>
            <th>メールアドレス</th>
            <th colspan="6"></th>
          </tr>
          <td><%= @user.user_name%></td>
          <td><%= @user.user_name_kana%></td>
          <td><%= @user.postcode%></td>
          <td><%= @user.address%></td>
          <td><%= @user.phone_number%></td>
          <td><%= @user.email%></td>
          <td><%= link_to "送付先リスト", user_destinations_path(current_user),class: "btn btn-default"%></td>
          <td><%= link_to "編集", edit_user_path(current_user),class: "btn btn-default" %></td>
          <td><%= link_to "退会", user_registration_path ,method: :delete, data: {confirm: "本当に退会しますか？"} ,class: "btn btn-default"%></td>
        </table>
        <h1>直近の購入履歴</h1>
        <table class="table">
          <tr>
            <th>受注日</th>
            <th>ステータス</th>
            <th>ユーザー名</th>
            <th>注文金額</th>
            <th colspan="4"></th>
          </tr>

          <% @orders.each do |order| %>
            <tr>
              <td><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
              <td>
              <% if order.status.to_i == 10 %>
                  受付済み
                <% elsif order.status.to_i == 20 %>
                  発送準備中
                <% elsif order.status.to_i == 30 %>
                  発送済み
                <% else %>
                  確認中
                <% end %>
              </td>
              <td><%= order.user.user_name %></td>
              <td><%= order.total_price %></td> 
              <td><%= link_to "詳細", order_path(order),class: "btn btn-default" %></td>
            </tr>
          <% end %>
        </table>
      <% end %> 
    </div>
  </div>
</body>