config/routes.rb
Rails.application.routes.draw do
  root 'roots#top'
  get '/about', to: 'roots#about'
  get '/admin_top', to: 'roots#admin_top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :destinations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update]
  resources :songs

  resources :labels, only: [:index, :new, :create, :edit, :update]
  resources :artists, only: [:index, :new, :create, :edit, :update]
  resources :orders

  get 'carts/confirm'
  get 'carts/thanks'
  resources :carts, only: [:show] do
    resources :cart_products, only: [:create, :update, :destroy]
  end


  get 'inquiries/new'
  get 'inquiries/confirm'
  post 'inquiries/confirm' => 'inquiries#confirm'
  get 'inquiries/thanks'

  get  'new' =>'inquiries#new'
  post 'thanks' => 'inquiries#thanks'

  # 開発環境メール確認用
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  post  'ajax_test/update', to: 'carts#update', as: 'ajax_test_update'
  post  'shakashaka', to: 'roots#shakashaka', as: 'ajax_shakashaka'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  belongs_to :user
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/label.rb
class Label < ApplicationRecord
has_many :products
validates :label_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products
  has_many :carts, through: :cart_products
  has_many :songs
  accepts_nested_attributes_for :songs
  has_many :artists, through: :songs
  belongs_to :label
  belongs_to :genre

  validates :explanation, presence:true,length: { maximum: 200 }
  validates :product_title, presence:true,length: { maximum: 50 }
  validates :product_price, presence: true
  validates :stock, presence: true

  # attachment :image
  has_one_attached :jacket_image

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :product

  validates :song_title, presence: true
  validates :track_order, presence: true
  validates :disk_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :user_name, presence: true, uniqueness: true, length: {maximum: 20}
  validates :user_name_kana, presence: true
  validates :postcode, length: {is:7}
  validates :address, presence: true, length: {maximum: 100}
  validates :phone_number, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  has_many :destinations
  has_one :cart, dependent: :destroy
  

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_admin
  def index
    @songs = Song.page(params[:page]).reverse_order
    @search = Song.ransack(params[:q])
    @result = @search.result.page(params[:page])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      flash[:notice] = "楽曲の登録に成功しました"
      redirect_to songs_path
    else
      render 'new'
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      flash[:notice] = "楽曲の更新に成功しました"
      redirect_to songs_path
    else
      render 'edit'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = "楽曲の削除に成功しました"
    redirect_to songs_path
  end

  private
    def song_params
      params.require(:song).permit(:song_title, :artist_id, :track_order, :product_id, :disk_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/songs/edit.html.erb
<div class="container">
  <h3>収録曲編集</h3>
  <% if @song.errors.any? %>
    <div class="error_explanation">
      <ul>
        <% @song.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for(@song) do |f| %>
    <div class="form-group">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ディスクNo</th>
            <th>曲順</th>
            <th>曲名</th>
            <th>アーティスト</th>
            <th>収録CD</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= f.text_field :disk_number %></td>
              <td><%= f.text_field :track_order %>
              <td><%= f.text_field :song_title %></td>
              <td><%= f.select :artist_id, options_from_collection_for_select(Artist.all, :id, :artist_name, @song.artist.id), {}, { class: 'searchable'} %></td>
              <td><%= f.select :product_id, options_from_collection_for_select(Product.all, :id, :product_title, @song.product.id), {}, { class: 'searchable'} %></td>
            </tr>
        </tbody>
      </table>
      <%= f.submit "更新", class:"btn btn-primary" %>
      <%= link_to "戻る", songs_path, class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

<script>
  $(function() {
    return $(".searchable").select2({
      width: 200,
      allowClear: true
    });
  });
</script>

app/views/songs/index.html.erb
<div class = "container">
  <div class="row">
    <h3 class = "col-xs-2">楽曲管理</h3>
    <div class = "col-xs-10"></div>
  </div>
  <div class="row text">
    <% provide(:song_title , 'All songs') %>
    <%= search_form_for @search  do |f| %>
      <div class="form-group col-xs-2">
        <p class="bg-primary text-left">曲名検索</p>
        <%= f.text_field :song_title_cont, class: "form-control", placeholder:"曲名" %>
      </div>
      <div class="form-group col-xs-2">
        <p class="bg-primary text-left">アーティスト名検索</p>
        <%= f.text_field :artist_artist_name_cont, class: "form-control", placeholder:"アーティスト名" %>
      </div>
      <div class="form-group col-xs-2">
        <p class="bg-primary text-left">CDタイトル名検索</p>
        <%= f.text_field :product_product_title_cont, class: "form-control", placeholder:"CDタイトル" %>
      </div>
      <div class="form-group col-xs-1">
        <div class = "text2"></div>
        <%= f.submit "検索", :class=>"btn btn-primary button-top"%>
      </div>
    <% end %>
    <div class="form-group col-xs-1">
      <div class = "text2"></div>
      <%= link_to "結果クリア", songs_path,:class=>"btn btn-primary button-top"%>
    </div>
    <div class="form-group col-xs-1">
      <div class = "text2"></div>
      <%= link_to "新規登録", new_song_path, class:"btn btn-primary button-top" %>
    </div>
  </div>
  <div class="row">
    <div class = "col-xs-2"></div>
      <table class="col-xs-7 table">
        <thead>
          <tr>
            <th>曲名</th>
            <th>アーティスト名</th>
            <th>収録CD</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @result.each do |song| %>
            <tr>
              <td class ="text1"><%= song.song_title %></td>
              <td class ="text1"><%= song.artist.artist_name %></td>
              <td class ="text1"><%= song.product.product_title %></td>
              <td class ="text1"><%= link_to "編集", edit_song_path(song), class:"btn btn-primary" %><%= link_to "削除", song_path(song), method: :delete, class:"btn btn-danger", data: { confirm: "本当に削除しますか？" } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="paginate"><%= paginate @songs %></div>
    </div>
  </div>
</div>

app/views/songs/new.html.erb
<div class="container">
  <h3>収録曲新規追加</h3>
  <% if @song.errors.any? %>
    <div class="error_explanation">
      <ul>
        <% @song.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for(@song) do |f| %>
    <div class="form-group">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ディスクNo</th>
            <th>曲順</th>
            <th>曲名</th>
            <th>アーティスト</th>
            <th>収録CD</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= f.text_field :disk_number %></td>
              <td><%= f.text_field :track_order %>
              <td><%= f.text_field :song_title %></td>
              <td><%= f.select :artist_id, options_from_collection_for_select(Artist.all, :id, :artist_name), {}, { class: 'searchable'} %></td>
              <td><%= f.select :product_id, options_from_collection_for_select(Product.all, :id, :product_title), {}, { class: 'searchable'} %></td>
            </tr>
        </tbody>
      </table>
      <%= f.submit "追加", class:"btn btn-primary" %>
      <%= link_to "戻る", songs_path, class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

<script>
  $(function() {
    return $(".searchable").select2({
      width: 200,
      allowClear: true
    });
  });
</script>