config/routes.rb
Rails.application.routes.draw do
  root 'roots#top'
  get '/about', to: 'roots#about'
  get '/admin_top', to: 'roots#admin_top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :destinations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update]
  resources :songs

  resources :labels, only: [:index, :new, :create, :edit, :update]
  resources :artists, only: [:index, :new, :create, :edit, :update]
  resources :orders

  get 'carts/confirm'
  get 'carts/thanks'
  resources :carts, only: [:show] do
    resources :cart_products, only: [:create, :update, :destroy]
  end


  get 'inquiries/new'
  get 'inquiries/confirm'
  post 'inquiries/confirm' => 'inquiries#confirm'
  get 'inquiries/thanks'

  get  'new' =>'inquiries#new'
  post 'thanks' => 'inquiries#thanks'

  # 開発環境メール確認用
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  post  'ajax_test/update', to: 'carts#update', as: 'ajax_test_update'
  post  'shakashaka', to: 'roots#shakashaka', as: 'ajax_shakashaka'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  belongs_to :user
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/label.rb
class Label < ApplicationRecord
has_many :products
validates :label_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products
  has_many :carts, through: :cart_products
  has_many :songs
  accepts_nested_attributes_for :songs
  has_many :artists, through: :songs
  belongs_to :label
  belongs_to :genre

  validates :explanation, presence:true,length: { maximum: 200 }
  validates :product_title, presence:true,length: { maximum: 50 }
  validates :product_price, presence: true
  validates :stock, presence: true

  # attachment :image
  has_one_attached :jacket_image

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :product

  validates :song_title, presence: true
  validates :track_order, presence: true
  validates :disk_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :user_name, presence: true, uniqueness: true, length: {maximum: 20}
  validates :user_name_kana, presence: true
  validates :postcode, length: {is:7}
  validates :address, presence: true, length: {maximum: 100}
  validates :phone_number, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  has_many :destinations
  has_one :cart, dependent: :destroy
  

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_correct_user, only: [:show]

  def show
    @cart = Cart.find_by(user_id: current_user.id)
    @cart_products = @cart.cart_products
    @sum_price = 0
    @cart_products.each do |cart_product|
      @sum_price += cart_product.quantity * cart_product.product.product_price
    end
  end

  def confirm
    @cart = Cart.find_by(user_id: current_user.id)
    session[:selected_dest_id] = "default"
    @cart_products = @cart.cart_products
    @sum_price = 0
    @cart_products.each do |cart_product|
      @sum_price += cart_product.quantity * cart_product.product.product_price
    end
    @order = Order.new

    #送付先選択用
    @user = User.find(current_user.id)
    @destinations = Destination.where(user_id:@cart.user.id)  #ほんとはカレントユーザー

  end

  def thanks
  end

  def update
    destination_id = params[:paramss]
    session[:selected_dest_id] = destination_id
    selected_dest = Destination.find(destination_id)
    results = { :message => selected_dest.destination_address }
    render partial: 'ajax_partial', locals: { :results => results }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/confirm.html.erb
<body class="confirm_body">
  <div class="container">
    <div class="row">
      <div class="order_price">
        <h1>注文確認</h1>
        <div class>
        <h3>ご請求額：<span class="total-price">¥<%= @sum_price.to_i %></span></h3>
        <%= form_for(@order) do |f| %>
          <%= link_to "カートに戻る", cart_path(@cart), class:"btn btn-default" %>
          <%= f.submit "注文を確定する", class:"btn btn-danger order-button" %>
        <% end %>
      </div>
    </div>

    <div class="destination-row">
      <div class="row">
        <div class="destination">
          <h4 id="updated_by_ajax">送付先：<%= @user.address %></h4> 
          <p class="btn btn-primary" id="dest-select">送付先を選択</p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="purchase-products">
        <h2>ご注文内容</h2>
        <% @cart_products.each do |cart_product| %>
          <div class="row purchase-product">
            <div class="cart_product_image">
              <% if cart_product.product.jacket_image.attached? %>
                <%= image_tag cart_product.product.jacket_image, class:"jacket-image", fallback:"img/no_image.png", :size => '300x300' %>
              <% else %>
                <%= image_tag 'img/no_image.png', class:"jacket-image", :size => '300x300' %>
              <% end %>
            </div>
            <div class="product-detail">
              <h3>
                <strong><%= link_to cart_product.product.product_title, product_path(cart_product.product) %></strong>
              </h3>
              <p>
                <% artist_ary = cart_product.product.artists.uniq %>
                <% artist_ary.each do |artist| %>
                  <%= artist.artist_name %>
                <% end %>
              </p>
              <p><%= cart_product.product.genre.genre_name %></p>
              <p>単価：¥<%= cart_product.product.product_price %></p>
              <p>数量：<%= cart_product.quantity %></p>
              <p>合計：¥<%= cart_product.product.product_price*cart_product.quantity %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>


<!-- 送付先選択用モーダル-->
  <div id="overlay">
    <div id="result">
      <h2 id="modal-title">送付先変更</h2>
      <div class="destinations">
        <input type="radio" name="dest_id" value="default" checked="checked">デフォルトの送付先
        <label>
          <div>
            <p>お名前：<%= @user.user_name %></p>
            <p>ご住所：<%= @user.address %></p> 
          </div>
        </label>
      </div>
      <% dest_count = 1 %>
      <% @destinations.each do |destination| %>
        <div class="destinations">
          <input type="radio" name="dest_id" value="<%= destination.id %>">送付先<%= dest_count %>
          <label>
            <div>
              <p>お名前：<%= destination.destination_name %></p>
              <p>ご住所：<%= destination.destination_address %></p>
            </div>
            <div class="request_ajax_update" >
              <%= button_to "この住所に変更",  {:action => "update", :paramss => destination.id }, {:remote => true, :class => "go btn btn-info" } %>
            </div>
          </label>
        </div>
        <% dest_count += 1 %>
      <% end %>
      <i class="fa fa-close", id="close"></i>
    </div>
  </div>
</body>

app/views/carts/show.html.erb
<body class="cart_show_body">
<div class="container">
  <div class="row">
    <h1 class="col-xs-7 cart-title">ショッピングカート</h1>

    <div class="col-xs-5">
      <h3>小計：<%= @sum_price %>円</h3>
      <%= link_to "買い物に戻る", products_path, class:"btn btn-default" %>
      <% if @cart_products.count != 0 %>
        <%= link_to "レジに進む", carts_confirm_path, class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="row center-block">
    <% if @cart_products.count == 0 %>
      <p>カートの中身は空です。</p>
    <% else %>
      <% @cart_products.each do |cart_product| %>
        <div class="cart_products">
          <div class="row">
            <div class="cart_product_image">
              <% if cart_product.product.jacket_image.attached? %>
                <%= image_tag cart_product.product.jacket_image, class:"jacket-image", fallback:"img/no_image.png", :size => '300x300' %>
              <% else %>
                <%= image_tag 'img/no_image.png', class:"jacket-image", :size => '300x300' %>
              <% end %>
            </div>
            <div class="cart-product-details">
              <h3>
                <strong><%= link_to cart_product.product.product_title, product_path(cart_product.product) %></strong>
              </h3>
              <p>
                <% artist_ary = cart_product.product.artists.uniq %>
                <% artist_ary.each do |artist| %>
                  <%= artist.artist_name %>
                <% end %>
              </p>
              <p><%= cart_product.product.genre.genre_name %></p>
              <p>単価：¥<%= cart_product.product.product_price %></p>
            </div>
            <div class="forms">
              <div class="cart_buttons">
                <%= form_for([@cart, cart_product]) do |f| %>
                  <%= f.label :quantity, "枚数" %>
                  <%= f.select :quantity, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5]] ,class:"form-control" %>
                  <%= f.submit "枚数変更を反映", class:"btn btn-info" %>
                <% end %>
              </div>
              <div class="cart_buttons"><%= link_to "カートから削除", cart_cart_product_path(@cart, cart_product), method: :delete, class:"btn btn-danger", data: { confirm: "本当に削除しますか？" } %></div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</body>

app/views/carts/thanks.html.erb
<div class="container">
  <div class="row">
    <div id="thanks-body">
      <div id="purchase-thanks">
        <h1>ありがとうございます。</h1>
        <h1>注文が確定されました。</h1>
      </div>
      <h3>到着までしばらくお待ちください。</h3>
    </div>
  </div>
</div>