config/routes.rb
Rails.application.routes.draw do
  root 'roots#top'
  get '/about', to: 'roots#about'
  get '/admin_top', to: 'roots#admin_top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :destinations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update]
  resources :songs

  resources :labels, only: [:index, :new, :create, :edit, :update]
  resources :artists, only: [:index, :new, :create, :edit, :update]
  resources :orders

  get 'carts/confirm'
  get 'carts/thanks'
  resources :carts, only: [:show] do
    resources :cart_products, only: [:create, :update, :destroy]
  end


  get 'inquiries/new'
  get 'inquiries/confirm'
  post 'inquiries/confirm' => 'inquiries#confirm'
  get 'inquiries/thanks'

  get  'new' =>'inquiries#new'
  post 'thanks' => 'inquiries#thanks'

  # 開発環境メール確認用
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  post  'ajax_test/update', to: 'carts#update', as: 'ajax_test_update'
  post  'shakashaka', to: 'roots#shakashaka', as: 'ajax_shakashaka'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  belongs_to :user
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/label.rb
class Label < ApplicationRecord
has_many :products
validates :label_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products
  has_many :carts, through: :cart_products
  has_many :songs
  accepts_nested_attributes_for :songs
  has_many :artists, through: :songs
  belongs_to :label
  belongs_to :genre

  validates :explanation, presence:true,length: { maximum: 200 }
  validates :product_title, presence:true,length: { maximum: 50 }
  validates :product_price, presence: true
  validates :stock, presence: true

  # attachment :image
  has_one_attached :jacket_image

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :product

  validates :song_title, presence: true
  validates :track_order, presence: true
  validates :disk_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :user_name, presence: true, uniqueness: true, length: {maximum: 20}
  validates :user_name_kana, presence: true
  validates :postcode, length: {is:7}
  validates :address, presence: true, length: {maximum: 100}
  validates :phone_number, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  has_many :destinations
  has_one :cart, dependent: :destroy
  

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShakaShaka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&amp;subset=japanese" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">
  </head>

  <body>
    <header class="navbar navbar-fixed-top">
      <div class="container">
        <nav class="navbar-nav navbar-right">
          <% if user_signed_in? %>
            <% user_name = current_user.user_name %>
          <% else %>
            <% user_name = "ゲスト" %>
          <% end %>
          <%= "ようこそ、#{user_name}さん" %>
        </nav>
      </div>
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <div>
            <%= link_to root_path do %>
              <%= image_tag("img/logo_shakashaka.png", :size => "150x80", :alt => "ロゴ") %>
            <% end %>
          </div>
        </nav>

        <nav>
          <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in?  %>
            <% if current_user.admin?%>
              <li><%= link_to " 管理者トップ", admin_top_path %></li>
              <li><%= link_to " ユーザー管理", users_path %></li>
              <li><%= link_to " 商品管理", products_path %></li>
              <li><%= link_to " 楽曲管理", songs_path %></li>
              <li><%= link_to " アーティスト管理", artists_path %></li>
              <li><%= link_to " レーベル管理", labels_path %></li>
              <li><%= link_to " 受注管理", orders_path %></li>
              <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li>
                <%= link_to products_path do %>
                  <div class="header-item">
                    <span class="header-icon"><i class="fa fa-music"></i></span>
                    <p>商品一覧</p>
                  </div>
                <% end %>
              </li>
              <li>
                <%= link_to cart_path(current_user.cart) do %>
                  <div class="header-item">
                    <span class="header-icon"><i class="fa fa-shopping-cart"></i></span>
                    <p>カート</p>
                  </div>
                <% end %>
              </li>
              <li>
                <%= link_to user_path(current_user.id) do %>
                  <div class="header-item">
                    <span class="header-icon"><i class="fa fa-user"></i></span>
                    <p>マイページ</p>
                  </div>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <div class="header-item">
                    <span class="header-icon"><i class="fa fa-sign-out"></i></span>
                    <p>ログアウト</p>
                  </div>
                <% end %>
              </li>
              <li>
                <%= link_to inquiries_new_path do %>
                  <div class="header-item">
                    <span class="header-icon"><i class="fa fa-envelope-o"></i></span>
                    <p>お問い合わせ</p>
                  </div>
                <% end %>
              </li>
            <% end %>
           <% else %>
            <li>
              <%= link_to products_path do %>
                <div class="header-item">
                  <span class="header-icon"><i class="fa fa-music"></i></span>
                  <p>商品一覧</p>
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to about_path do %>
                <div class="header-item">
                  <span class="header-icon"><i class="fa fa-sticky-note-o"></i></span>
                  <p>About</p>
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <div class="header-item">
                  <span class="header-icon"><i class="fa fa-user-plus"></i></span>
                  <p>会員登録</p>
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <div class="header-item">
                  <span class="header-icon"><i class="fa fa-sign-in"></i></span>
                  <p>ログイン</p>
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to inquiries_new_path do %>
                <div class="header-item">
                  <span class="header-icon"><i class="fa fa-envelope-o"></i></span>
                  <p>お問い合わせ</p>
                </div>
              <% end %>
            </li>
           <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="flash-messages">
          <% if flash[:notice] %>
           <p class="notice"><%= flash[:notice] %></p>
          <% end %>
          <% if flash[:danger] %>
           <p class="danger"><%= flash[:danger] %></p>
          <% end %>
        </div>
      </div>
    </div>

    <%= yield %>

    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <div class="footer pull-right">
            <p>CopyRight HotelSeminal</p>
          </div>
        </div>
      </div>
    </div>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  </body>
</html>